### ISSUE TITLE
glados::cuda::launch-kernel does not create good configuration

### ISSUE THREAD

**Issue by tobiasfrust** [HZDR-FWDF/GLADOS#11]
The block sizes which are computed for 2- or 3-dimensional kernels are not multiples of 32.
 e.g.: 432x500 2-dimensional threads shall be created which results in this configuration:
- Block size: (2,2) -> no multiple of 32
- Grid size: (216,250)

When invoking the kernel with a block size of (16,16) and (27, 32) the average kernel runtime is nearly 10 times faster.

**Comment by j-stephan** [comment]
Proposed new algorithm:

1. Set a fixed blocksize (e.g. 16x16 for 2D or 16x16x2 for 3D).
2. Calculate the gridsize based upon the blocksize and the input sizes.
3. Launch the kernel.

As the launch functions are designed to be "fire and forget" functions I don't see major performance issues with this approach. If your (not you personally but in general) kernel really really needs the performance you should hand-tune it anyway.

Thoughts?

**Comment by tobiasfrust** [comment]
Yes, the proposed algorithm will completeley suffice. 
The function must definitely forsure that the blocksize is a multiple of 32, this is a prerequisit of CUDA for reasonable performance (Exceptions confirm the rule ;)). I think the user expects, that the basic requirements are met, if he calls this function.
Of course, all further or special tweaks need to be defined by the user, but this prerequisite needs to be fulfilled by this launch function.

**Comment by j-stephan** [comment]
Thanks for the notice. My old laptop is now able to reconstruct a 1070x1070x1033 volume 20% faster :).

**Comment by BieberleA** [comment]
Perfect!

**Comment by BieberleA** [comment]
Could you please perform timing measurements on K20c and GTC1080 with PARIS using the new structured GLADOS?

**Comment by j-stephan** [comment]
Sure, I'll try to squeeze it in on Monday or so. Otherwise in the new year, is that sufficient?

**Comment by j-stephan** [comment]
See HZDR-FWDF/PARIS#29 for further reference.
