### ISSUE TITLE
Modify the name of the template.

### ISSUE THREAD

**Issue by BieberleA** [HZDR-FWDF/GLADOS#6]
... as I described in the email a few minutes ago.

**Comment by BieberleA** [comment]
What about: **RO**ssendorfer **M**ulti pr**O**cess and mu**L**ti gp**U** framework **S**ystem: ROMOLUS (https://en.wikipedia.org/wiki/Romulan#Homeworld)

**Comment by DominicWindisch** [comment]
I also got some nerdy suggestions... :)

- **NOMAD**: **N**ew **O**pen source **M**ultiple purpose **A**ccelerated computing framework **D**resden (http://memory-alpha.wikia.com/wiki/Nomad)
- **GLADOS-DD**: - **G**eneral purpose **L**ibrary for **A**ccelerated computing on **D**iverse c**O**nfigurations using asynchronous **S**tages - **D**res**D**en (https://en.wikipedia.org/wiki/GLaDOS)
- **FRINKIAC**: - **F**lexible **R**ossendorf **I**mplementation of a ge**N**eral purpose framewor**K** for **I**ntelligently **A**ccelarated **C**omputing (https://en.wikipedia.org/wiki/Frinkiac)

**Comment by j-stephan** [comment]
Names which should be excluded:

Vulkan (a new Graphics API)
Khronos (the organization behind Vulkan, OpenGL and most importantly, OpenCL)

**Comment by j-stephan** [comment]
* **PSI** - **P**rogrammable **S**treaming **I**nterface
* **DS16** - *D*ata *S*treaming *B*uilding *B*locks (B + B = 8 + 8 = 16) [DS = reference to DS9]
* **Glados** - **G**eneral purpose **L**ibrary for **A**synchronous **D**ata **O**perations and **S*treaming

**Comment by BieberleA** [comment]
I like GLADOS but the real background is very high level and I'm not sure if we can/should use. PSI is to close to the Paul Scheer Institute (https://www.psi.ch/science/facilities). So NOMAD could be possible. But I prefer a name without Dresden.

**Comment by BieberleA** [comment]
Do all agree with: Glados - General purpose Library for Asynchronous Data Operations and Streamings?

**Comment by tobiasfrust** [comment]
I would use Streaming as singular; furthermore, General purpose could be replaced by Generic. 
So my suggestion would be: Generic Library for Asynchronous Data Operations and Streaming.
It's a little shorter than the other acronym. 
A short research for existing brands using this acronym did not result in any hits (https://register.dpma.de/DPMAregister/marke/einsteiger)

So, I like it!

**Comment by j-stephan** [comment]
Me too.

**Comment by DominicWindisch** [comment]
Me too.

**Comment by j-stephan** [comment]
Done.
