### ISSUE TITLE
Update license texts.

### ISSUE THREAD

**Issue by j-stephan** [HZDR-FWDF/GLADOS#7]
They still have the "ddrf" name.

**Comment by BieberleA** [comment]
Do I have to do something or do you change the required text passages?

**Comment by j-stephan** [comment]
I plan to do this on Thursday. I won't stop you if you want to do it yourself, though :-) Every file in the repository has a license header which contains the name exactly three times. Those occurences have to be changed.

**Comment by BieberleA** [comment]
Shell we do it in privacy mode temporarily?

**Comment by j-stephan** [comment]
I don't think that will be necessary, the license itself is still valid. Its merely cosmetical.
